jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

orbs:
  node: circleci/node@4.1.0

version: 2.1

workflows:
  node-tests:
    jobs:
      - test
